# Generated by Django 5.2.3 on 2025-07-22 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_marca_proveedor_remove_producto_autor_and_more'),
    ]

    operations = [
    
        migrations.AlterField(
            model_name='imagen',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto'),
        ),
        
    ]
