# Generated by Django 5.2.3 on 2025-07-25 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_marca_proveedor_remove_producto_autor_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='carrito',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        
    ]
